### ISSUE TITLE
Deployed instances do not have an instance_uuid set

### ISSUE THREAD

**Issue by juliakreger** [openshift-metal3/terraform-provider-ironic#11]
When instances are requested to be deployed, they should ideally have an instance_uuid set as otherwise ironic will not collect sensor data from a remote host without an instance_uuid set.

This flag also allows for other ironic API consumers to understand that the node is in use by an API client.

**Comment by stbenjam** [comment]
This provider now relies on the new allocation feature, which sets the instance_uuid for a deployment.
