### ISSUE TITLE
Available case automatic delete prevents re-use

### ISSUE THREAD

**Issue by juliakreger** [openshift-metal3/terraform-provider-ironic#6]
In the metalkube case, it kind of works to just automatically an "available" node, however in a general use case, an available node is free for re-use in an ironic API endpoint. I don't think this provider should delete the node from ironic.

**Comment by stbenjam** [comment]
Are you referring to this? 

https://github.com/openshift-metalkube/terraform-provider-ironic/blob/master/ironic/resource_ironic_node_v1.go#L537-L540

If you run `terraform destroy` it needs to put things in the state that existed before a user could run `create`, i.e. the nodes need to be deleted and removed, so create could be run again from scratch.

I am wondering if the terraform provider should have two different resources: one for the baremetal hardware node, and one for a deployment that consumes a node, so you don't necessarily have to manage the hardware (i.e. it could already be created in ironic via discovery) - what do you think about that?

**Comment by juliakreger** [comment]
I think that would be ideal because then just selecting and consuming a free hardware node becomes fairly simple and can be re-used easily allowing better general re-use of  an ironic provider's code and could... eventually... allow an operator to leverage an already deployed ironic/configured ironic.

**Comment by stbenjam** [comment]
Ok, I think that make sense.  The installer would even be able to use an existing Ironic, it wouldn't have to be an opreator.  I wrote some thoughts about how the installer should get hardware information in this PR: https://github.com/openshift-metalkube/kni-installer/pull/25/files#diff-9ffecdd580b2cb3a1e0e5c2fc92faccfL107

If the hardware is already in Ironic, it makes it very easy to prompt the user for just the bare minimum details - basically just BMC creds.

**Comment by stbenjam** [comment]
With a the separation of deployments from the node objects, "deletion" of a deployment doesn't delete the node object, it makes it available for use again.  Only explicitly destroying the node object itself will delete it.
